name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:      

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "$(date)" >> log.txt  

      - name: Commit & Push
        run: |
          git config user.name "Trigger-1111"
          git config user.email "231469708+Trigger-1111@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "commit: $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
